# Generated by Django 3.0.10 on 2020-10-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='extagram/%Y/%m/%d'),
        ),
    ]
